### ISSUE TITLE
Division by negative numbers 

### ISSUE THREAD

**Issue by brainded-boi** [Darkempire78/OpenCalc#181]
**Describe the bug**
Division by negative numbers

**To Reproduce**
When trying 9/-3, it replaces the / with a -

**Expected behavior**
-3, but the result is 9-3 = 6

**Screenshots/videos**

https://user-images.githubusercontent.com/96941634/220725194-ae5e1d56-0bac-4784-84d2-fc25fe46ac87.mp4

**Smartphone**
 - Device: realme narzo 30a
 - OS: Android 11
 - Version: 2.1.2
 - Language: English

**Comment by VibrantTreeStump** [comment]
Imo this is the expected behaviour. The way around this would be to add fractions to the calculator [like this](https://user-images.githubusercontent.com/82000085/220966961-725883d3-5ef7-47f0-9de8-61a65546772a.png). This would necessitate adding arrow keys or touch functionality for that purpose. If the divide sign is to be used, the way around this is to parenthesize the expression as 9÷(-3)

**Comment by Markus40** [comment]
Other probably related combinations that do not work:
1*(sin(2))
1+sin(2)
1-sin(2)
2^sin(2)
(sin(2))
