### ISSUE TITLE
Opencalc automatically reads clipboard 

### ISSUE THREAD

**Issue by gnuchu** [Darkempire78/OpenCalc#232]
App auto reads the clipboard. This is a bit creepy and wrong. Clipboard should be only accessed when the user tries to paste.

**Comment by Markus40** [comment]
I also had the problem, but could not reproduce it at the time. Now, after some experimentation, I have succeeded.

It only happens when there is new text in the clipboard and then one of the buttons is touched.

**Comment by Darkempire78** [comment]
The problem is that I do not think that I can disable the toast (https://developer.android.com/develop/ui/views/touch-and-input/copy-paste#PastingSystemNotifications)
The app get the latest element from your clipboard to compare it with tge new entry in the order to know if you pasted something into the input

Idk what to do for the moment

**Comment by Markus40** [comment]
It is unlikely that you will ever be able to disable it, as it is intended as a security feature.

Why does the app need to know if the input is from the clipboard? The evaluation of the calculation can be the same. If you do additional cleanup, you can apply it to all input, the performance penalty should be minimal.
