### ISSUE TITLE
The formula was wrong with 90% : (90 - 90)

### ISSUE THREAD

**Issue by ChinhQT** [Darkempire78/OpenCalc#281]
Describe the bug
The formula was wrong with 90% : (90 - 90)
The app's result is = Divide by 0
But other app, the expected result is = Divide by 0

To Reproduce

Go to the application
Click on the expression 90% : (90 - 90)
Check the result and see error
Expected behavior
The expected result is = Divide by 0

**Comment by Loading102** [comment]
I may be misunderstanding your problem, but from what you write the expected behavior is exactly the same as the app's result.
> The app's result is = Divide by 0
> But other app, the expected result is = Divide by 0

I also don't see how is this result wrong - 90% : (90 - 90) is the same as 0.9 / 0, which is a mathematical error, and so is impossible to calculate - giving the result of "can't divide by 0"

**Comment by Darkempire78** [comment]
I do not understand the problem, all seems to work...
