### ISSUE TITLE
Play protect error!

### ISSUE THREAD

**Issue by anjanraj027** [Darkempire78/OpenCalc#3]
Why does it ask for any kind of data to send?
And it's blocked in play protect after the update...![Screenshot_20220727-231537_Google Play Store.png](https://user-images.githubusercontent.com/75117277/181334705-aa003b9a-3a99-4445-a656-053194a8c236.png)![Screenshot_20220727-231524![Screenshot_20220727-231524_Google Play Store~01.png](https://user-images.githubusercontent.com/75117277/181338826-0458ed9b-2f49-4bde-9a98-d33c7061a75e.png)

**Comment by Darkempire78** [comment]
Because you installed the .apk which is not from the Google play store. Click on "Don't send" then "Install anyway". This is not a bug but just Google protect which want to "protect" your frol aginst virus (caused this app is not on Google play store). It's normal when you install an apk, don't worry

**Comment by Darkempire78** [comment]
I have no idea 😬

**Comment by Leif-W** [comment]
I installed from F-Droid, not side load apk.  F-Droid reports no permissions required.  Play Protect doesn't see or scan or care for me.
