### ISSUE TITLE
Bug: Enter .0xyz and the 0 disappears when you hit x

### ISSUE THREAD

**Issue by Leif-W** [Darkempire78/OpenCalc#56]
It will work correctly if using the leading zero.

Examples:

Intended: 5 * .02 = 0.1

Actual: 5 * .2 = 1

Workaround: 5 * 0.02 = 0.1

Surprising behavior.  Entering a leading zero is optional and should be implied internally as soon as a decimal point is reached.  After a decimal point, stop elimination of zeroes incorrectly treated as leading zeroes.

**Comment by araymondmiracosta** [comment]
@Darkempire78, I have been plagued by this problem as well. I believe the issue is in `NumberFormatter.kt`.

On line 9, the following regex statement is present:
`([0-9]+\\$decimalSeparatorSymbol[0-9]+)|([0-9]+)`

After modifying the statement in a regex editor, I found that removing "\\$" seems to resolve the issue. I have not compiled the application with this modification, but it should be a step in the right direction.
