### ISSUE TITLE
Turn circular button to square on press

### ISSUE THREAD

**Issue by Paol-M** [Darkempire78/OpenCalc#6]
When the circular buttons are pressed on Google's app the circle turns into a square (with rounded corners)

**Comment by Darkempire78** [comment]
I don't find that very beautiful and I don't really see how to do that. I don't think I would work on it

**Comment by Leif-W** [comment]
Some visual indicator of button press is necessary from a UX perspective.  Currently, the color changes.  But since fingertips are also round and cover the button, it may be harder to see.  Other UI options are typically to make the button size grow a bit, or add a border, or give a shaded border and a slight x-y coordinate offset to simulate a 3D button press.  I haven't seen the app mentioned above, but squaring the circle would solve the problem of ensuring the change state of a finger-sized circle is more noticable when rendered as a larger-than-finger sized square.  Agreed, it has some subjective quirkiness.  But it is nonetheless a clever and reasonable design pattern, valid for consideration, or discussion, possibly improving upon, not summarily dismissed due to subjective aesthetics or implementation unfamiliarity.
